name: Linting

on:
  push:
    branches:
      - master
      - next
      - beta
  pull_request:
    branches:
      - master
      - next
      - beta

jobs:
  check-commit:
    name: Check Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0

      - name: Check Commit Messages
        uses: wagoid/commitlint-github-action@v6

  lint-dockefie:
    name: Linting Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4 
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./dockeriles
          recursive: true